-- Schema for subscriptions and the one-month free trial.
create table if not exists public.subscription_plans (
	id bigint generated by default as identity primary key,
	name text not null,
	price numeric(12, 2) not null default 0,
	duration_days integer not null,
	is_free boolean not null default false,
	created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	plan_id bigint references public.subscription_plans(id),
	status text not null default 'pending',
	is_free_trial boolean not null default false,
	start_date timestamptz,
	expires_at timestamptz,
	created_at timestamptz not null default now()
);

create table if not exists public.payments (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	subscription_id bigint references public.subscriptions(id) on delete cascade,
	amount numeric(12, 2) not null default 0,
	provider text,
	status text not null default 'pending',
	created_at timestamptz not null default now()
);

-- Make existing installations compatible with the frontend's canonical date field.
alter table public.subscriptions add column if not exists expires_at timestamptz;
alter table public.subscriptions add column if not exists is_free_trial boolean not null default false;

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create unique index if not exists one_free_trial_per_user_idx
	on public.subscriptions(user_id) where is_free_trial = true;

insert into public.subscription_plans (name, price, duration_days, is_free)
select 'Essai gratuit', 0, 30, true
where not exists (
	select 1 from public.subscription_plans where is_free = true
);

update public.subscription_plans
set duration_days = 30
where is_free = true;

-- Migrate old installations that used end_date.
do $$
begin
	if exists (
		select 1 from information_schema.columns
		where table_schema = 'public' and table_name = 'subscriptions' and column_name = 'end_date'
	) then
		execute 'update public.subscriptions set expires_at = end_date where expires_at is null';
	end if;
end $$;

alter table public.subscription_plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;

drop policy if exists "Anyone can read subscription plans" on public.subscription_plans;
create policy "Anyone can read subscription plans"
	on public.subscription_plans for select to authenticated using (true);

drop policy if exists "Users can read own subscriptions" on public.subscriptions;
create policy "Users can read own subscriptions"
	on public.subscriptions for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can create own subscriptions" on public.subscriptions;
create policy "Users can create own subscriptions"
	on public.subscriptions for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update own subscriptions" on public.subscriptions;
create policy "Users can update own subscriptions"
	on public.subscriptions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can read own payments" on public.payments;
create policy "Users can read own payments"
	on public.payments for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can create own payments" on public.payments;
create policy "Users can create own payments"
	on public.payments for insert to authenticated with check (auth.uid() = user_id);
